INSERT INTO COUNTRIES VALUES(COUNTRIES_SEQ.NEXTVAL, 'India', '+91', 'IN');
INSERT INTO COUNTRIES VALUES(COUNTRIES_SEQ.NEXTVAL, 'United States', '+1', 'US');
INSERT INTO COUNTRIES VALUES(COUNTRIES_SEQ.NEXTVAL, 'Nepal', '+977', 'NP');
INSERT INTO COUNTRIES VALUES(COUNTRIES_SEQ.NEXTVAL, 'Sri Lanka', '+94', 'SL');
INSERT INTO COUNTRIES VALUES(COUNTRIES_SEQ.NEXTVAL, 'Bhutan', '+975', 'BT');


INSERT INTO USER_ROLES VALUES(USER_ROLES_SEQ.NEXTVAL, 'NONE');
INSERT INTO USER_ROLES VALUES(USER_ROLES_SEQ.NEXTVAL, 'MEMBER');
INSERT INTO USER_ROLES VALUES(USER_ROLES_SEQ.NEXTVAL, 'LIBRARIAN');
INSERT INTO USER_ROLES VALUES(USER_ROLES_SEQ.NEXTVAL, 'ADMIN');


INSERT INTO USER_AC_STATUS VALUES(USER_AC_STATUS_SEQ.NEXTVAL, 'ACTIVE');
INSERT INTO USER_AC_STATUS VALUES(USER_AC_STATUS_SEQ.NEXTVAL, 'CLOSED');
INSERT INTO USER_AC_STATUS VALUES(USER_AC_STATUS_SEQ.NEXTVAL, 'REVOKED');
INSERT INTO USER_AC_STATUS VALUES(USER_AC_STATUS_SEQ.NEXTVAL, 'LOCKED');
INSERT INTO USER_AC_STATUS VALUES(USER_AC_STATUS_SEQ.NEXTVAL, 'INCOMPLETE');


INSERT INTO BOOK_INSTANCE_STATUS VALUES(BOOK_INSTANCE_STATUS_SEQ.NEXTVAL, 'ISSUED');
INSERT INTO BOOK_INSTANCE_STATUS VALUES(BOOK_INSTANCE_STATUS_SEQ.NEXTVAL, 'AVAILABLE');
INSERT INTO BOOK_INSTANCE_STATUS VALUES(BOOK_INSTANCE_STATUS_SEQ.NEXTVAL, 'REMOVED');


